const HeroSection = () => {
    return (
        <section className="relative flex items-center justify-center p-16 bg-gray-200 h-">
            <div className="absolute inset-0 bg-[url(/fundoHero5.png)] bg-cover bg-center z-0 " />
            <h1>Hero</h1>
            <p >Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel sequi tenetur suscipit asperiores doloremque ut enim voluptatum ab beatae rem aut earum, temporibus explicabo amet quam eius. Libero ratione at eligendi aspernatur. Tempore fuga natus veniam sequi dolores tenetur ea distinctio, vitae esse, reiciendis voluptatem, dignissimos accusantium quod eveniet similique veritatis illum laudantium repudiandae culpa! Doloribus, quos praesentium commodi consectetur alias vero excepturi quaerat aliquam accusamus velit a natus deserunt perspiciatis vitae repudiandae. Est at impedit eius fuga expedita id, quas ab ipsa nam ipsam consectetur eligendi consequatur alias dicta vero rerum, aspernatur recusandae repudiandae odio eveniet incidunt voluptatibus, architecto eum. At veniam vitae quod maiores maxime sit dignissimos reprehenderit dolor provident. Obcaecati accusantium, dolores ipsam tenetur vel amet aspernatur totam eos, voluptate tempora veritatis aut quis, necessitatibus quod reiciendis nemo cum architecto. Voluptate, illum facilis aliquid beatae ducimus optio eius maiores obcaecati enim, quod exercitationem earum velit nulla laboriosam! Quod blanditiis itaque expedita ut voluptatem, nulla veritatis laboriosam minus doloremque distinctio ipsum odio tempore, eveniet accusamus? Modi at quo neque saepe ipsam earum aut quibusdam reiciendis sed, nam sapiente suscipit nulla fugit cupiditate necessitatibus unde maiores eum. Nesciunt rerum, enim, quidem blanditiis voluptatem expedita voluptatum eos libero deserunt eum repellat recusandae ipsa assumenda aut nostrum aspernatur corrupti sed sit obcaecati? Eaque cum quam fugiat, doloremque aliquid nisi rem earum expedita ellat, eveniet necessitatibus veritatis possimus eos dicta. Non, nisi sapiente? Itaque, maiores officia. Quis minus quisquam cum distinctio laudantium nisi perspiciatis eaque tempore nesciunt quas, voluptatum quidem? Obcaecatdoiashdsaioudhasioudhsgduisahdbuoaakifuhsbifukedhfikaccusamus excepturi voluptatibus aliquid?
                voluptatem, nulla veritatis laboriosam minus doloremque distinctio ipsum odio tempore, eveniet accusamus? Modi at quo neque saepe ipsam earum aut quibusdam reiciendis sed, nam sapiente suscipit nulla fugit cupiditate necessitatibus unde maiores eum. Nesciunt rerum, enim, quidem blanditiis voluptatem expedita voluptatum eos libero deserunt eum repellat recusandae ipsa assumenda aut nostrum aspernatur corrupti sed sit obcaecati? Eaque cum quam fugiat, doloremque aliquid nisi rem earum expedita veritatis quod, placeat fugit quisquam officiis? Quam neque officiis sit enim inventore obcaecati optio quasi vitae doloribus qui dignissimos unde eligendi mollitia saepe vero itaque soluta, cupiditate rem voluptatum, blanditiis eos cumque. Nihil ex voluptatibus iure itaque recusandae ea quaerat dolor reiciendis sed nostrum hic, molestias totam doloremque, explicabo autem placeat pariatur debitis quae ab provident? Maiores suscipit aspernatur ut, doloribus in tempore et placeat molestias? Omnis nemo maxime cupiditate illum, quod, sunt laborum, ad facere dignissimos explicabo repudiandae debitis impedit tempora. Quisquam ratione nesciunt perferendis modi sunt reiciendis doasdnjasjdhsaoiudhsaoiudhasoudihadoiuashdisdasouhdausdhgasuidgsauidgsaudkisasdoiashdoiashdsaioudhasioudhsgduisahdbuoaakifuhsbifukedhfikores suscipit aspernatur ut, doloribus in tempore et placeat molestias? Omnis nemo maxime cupiditate illum, quod, sunt laborum, ad facere dignissimos explicabo repudiandae debitis impedit tempora. Quisquam ratione nesciunt perferendis modi sunt reiciendis do
                tur ut, doloribus in tempore et placeat molestias? Omnis nemo maxime cupiditate illum, quod, sunt laborum, ad facere dignissimos explicabo repudiandae debitis impedit tempora. Quisquam ratione nesciunt perferendis modi sunt reiciendis do
                voluptatem, nulla veritatis laboriosam
                voluptatem, nulla veritatis laboriosam minus doloremque distinctio ipsum odio tempore, eveniet accusamus? Modi at quo neque saepe ipsam earum aut quibusdam reiciendis sed, nam sapiente suscipit nulla fugit cupiditate necessitatibus unde maiores eum. Nesciunt rerum, enim, quidem blanditiis voluptatem expedita voluptatum eos libero deserunt eum repellat recusandae ipsa assumenda aut nostrum aspernatur corrupti sed sit obcaecati? Eaque cum quam fugiat, doloremque aliquid nisi rem earum expedita veritatis quod, placeat fugit quisquam officiis? Quam neque officiis sit enim inventore obcaecati optio quasi vitae doloribus qui dignissimos unde eligendi mollitia saepe vero itaque soluta, cupiditate rem voluptatum, blanditiis eos cumque. Nihil ex voluptatibus iure itaque recusandae ea quaerat dolor reiciendis sed nostrum hic, molestias totam doloremque, explicabo autem placeat pariatur debitis quae ab provident? Maiores suscipit aspernatur ut, doloribus in tempore et placeat molestias? Omnis nemo maxime cupiditate illum, quod, sunt laborum, ad facere dignissimos explicabo repudiandae debitis impedit tempora. Quisquam ratione nesciunt perferendis modi sunt reiciendis do
                voluptatem, nulla veritatis laboriosam minus doloremque distinctio ipsum odio tempore, eveniet accusamus? Modi at quo neque saepe ipsam earum aut quibusdam reiciendis sed, nam sapiente suscipit nulla fugit cupiditate necessitatibus unde maiores eum. Nesciunt rerum, enim, quidem blanditiis voluptatem expedita voluptatum eos libero deserunt eum repellat recusandae ipsa assumenda aut nostrum aspernatur corrupti sed sit obcaecati? Eaque cum quam fugiat, doloremque aliquid nisi rem earum expedita veritatis quod, placeat fugit quisquam officiis? Quam neque officiis sit enim inventore obcaecati optio quasi vitae doloribus qui dignissimos unde eligendi mollitia saepe vero itaque soluta, cupiditate rem voluptatum, blanditiis eos cumque. Nihil ex voluptatibus iure itaque recusandae ea quaerat dolor reiciendis sed nostrum hic, molestias totam doloremque, explicabo autem placeat pariatur debitis quae ab provident? Maiores suscipit aspernatur ut, doloribus in tempore et placeat molestias? Omnis nemo maxime cupiditate illum, quod, sunt laborum, ad facere dignissimos explicabo repudiandae debitis impedit tempora. Quisquam ratione nesciunt perferendis modi sunt reiciendis do</p>
            <p>lorem</p>
        </section>
    )
}

export default HeroSection